name: Build

on: [push]

jobs:
  build:
    name: Build Content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          check_hidden: true
          path: docs
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@main
        with:
          path: docs
      - uses: actions/setup-go@v5
        with:
          go-version: 'latest'
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build
