name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      unpackerr_branch:
        description: "The branch to read unpackerr's definitions.yml from"
        required: true
        default: "main"
      branch:
        description: "The local branch to deploy from"
        required: true
        default: "main"
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ inputs.branch || 'main' }}
      - uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        env:
          UNPACKERR_BRANCH: ${{ inputs.unpackerr_branch || 'main' }}
        run: yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: build
